### PR TITLE
build: Do not set -g, -O3 and -Werror CFLAGS

### PR DESCRIPTION
**Pull request by Elv13**
Hello, here are a few changes to the default CFLAGS

## Why Werror

With each new compiler version, your code "break" and fail to compile. It is true that it's a sometime a "bug" in the code and need visibility to get fixed. However, Werror should *always* be a local CFLAGS and not a project one, see Google for endless people arguing back and forth and removing Werror is now the prevalent winner of that argument. In the latest GCC, it fails to compile because the fwrite result in unchecked. Even if you fix this in new releases, you cannot fix the past and all existing releases used in stable products suddenly fail to compile, wasting everybody time.

## Why -g

This should be decided by the one who compiles the code. Some people want small and pre-stripped binaries and appending this to the CFLAGS breaks the standard way of achieving this. Prepend it if you wish, but please do not append it.

## Why -O3

On many systems with limited cache or higher memory latency, `O3` is slower than `O2`, so IMHO it should not be hardcoded. In my case I used `Os` and it's faster. The `O` value should be left to the system, not hardcoded.

### CODE REVIEW

**Comment by redboltz** [comment]
@Elv13 , thank you for sending the PR.
Basically I agree with you. The opitons should be removed from CMakeLists.txt.
I found the same options settings are in CMakeLists.txt in sub directories.

However, travis-ci and appveyor need to `-Werror` because they regard to success even if the code has warnings. I think that `-Werror` should be added via `.travis.yml` and `appveyor.yml`.

**Comment by Elv13** [comment]
> However, travis-ci and appveyor need to -Werror

Sure, of course, it's where those options belong, that's the point of the PR ;). Do you want me to add more commits to the `.travis.yml` or do you wish to do it yourself and the the opportunity to add more developer friendly flags like `-ggdb3`, `-fsanitize=address`, `--coverage`, and other scan-build goodies?

**Comment by redboltz** [comment]
> Do you want me to add more commits to the .travis.yml or do you wish to do it yourself
Could you update other `CMakeLists.txt`s, `.travis.yml`, and `appveyor.yml` ?

> and the the opportunity to add more developer friendly flags like -ggdb3, -fsanitize=address, --coverage, and other scan-build goodies?

It's nice to have. But I think that adding them should be another pull request. The pull request is welcome :)

NOTE: Some of travis-ci build contains `valgrind` check. I'm not sure but perhaps it is not work well with `-fsanitize=address`.

**Comment by redboltz** [comment]
I removed `-O3 -g -Werror` from other CMakeLists.txt in the sub directories.
I added `-g -Werror` to `.travis.yml`.

Thank you @Elv13 !

`-ggdb3, -fsanitize=address, --coverage` is not included. They should be other pull requests.

**Pull request merged**
