### PR TITLE
Migrate to gha

### PR DESCRIPTION
**Pull request by redboltz**

### CODE REVIEW

**Comment by redboltz** [comment]
I'm going to migrate from travis-ci to github actions.
I don't decide how to treat appveyor yet.

It seems that in order to activate github actions, at least one commit (merge) that includes  `.github/workflows/gha.yml`. (We can use any name. I use `gha.yml` as an acronym of GitHubActions.)

I got the following runtime error on MSVC build on Windows.
https://github.com/redboltz/msgpack-c/runs/360668989#step:4:1899

**Comment by redboltz** [comment]
@ygj6, if you have time, could you analyze this?

**Comment by redboltz** [comment]
On appveyor, no errors are reported. (Not the same compiler version)
https://ci.appveyor.com/project/redboltz/msgpack-c-pnitn/builds/29716974/job/bkak7k2qpsw37r9t#L1882

**Comment by ygj6** [comment]
When I changed the `runs-on` of windows job from `windows-latest` to `windows-2016`, the job ran smoothly: https://github.com/ygj6/msgpack-c/commit/3de81c95f25aa7edadcf81cce5991f1c75d3246d/checks?check_suite_id=372969113
`windows-latest` corresponds to `Visual Studio 2019` and `windows-2016` corresponds to `Visual Studio 2017`. Maybe we bump into a bug when using visual studio 2019.  I will study it next time.

**Comment by redboltz** [comment]
@ygj6, thank you for the comment. It is very helpful.

For mac and linux builds, github actions covers all of existing test. So I removed travis-ci support.

For windows, older versions of MSVC (2010 to 2015) are covered by appveyor. And newer version (2017) is covered by github actions.

We still have MSVC 2019 issue, but I merge the PR.

**Pull request merged**
