### PR TITLE
cmake: Enable all Boost tests on CI

### PR DESCRIPTION
**Pull request by herbrechtsmeier**
At the moment the CI doesn't test all Boost test and examples. Make all Boost components mandatory if MSGPACK_BOOST is ON. Additionally disable boost on AppVeyor when the compiler don't match the default compiler because the pre-installed software is only compiled with the default compiler.

### CODE REVIEW

**Comment by herbrechtsmeier** [comment]
The Travis CI errors aren't introduced by this PR. They wasn't tested before this PR.

**Comment by redboltz** [comment]
@herbrechtsmeier , thank you for sending the PR. I understand the situation.

I think the fix for old MSVC on appveryor is OK.
I will fix stream_unpack error.

**Comment by redboltz** [comment]
@herbrechtsmeier , it seems that there are two kinds of errors. One is unused parameter warnings, the other is default construction error.

It only happens clang++. On g++ with `X3_PARSE="ON"` build, it successfully finished.


So I updated clang version to 3.9, then the default construction error is disappeared. I guess that it is clang's bug. (I don't checked bug report).

I also added warning suppression pragma for clang. Then the warnings are disappeared.

Here is the updated branch:

https://github.com/redboltz/msgpack-c/commits/herbrechtsmeier-ci

However, I don't know the way to updated osx version of clang on travis-ci.

The current build status is https://travis-ci.org/redboltz/msgpack-c/builds/232330563

I will study more how to update osx clang on travis-ci. If I won't find it, I will remove `X3_PARSE="ON"` from failing build.

**Comment by redboltz** [comment]
I couldn't find the way to update osx clang on travis-ci, so I removed X3_PARSE from the build

**Pull request merged**
