### PR TITLE
Adding an example of sax like parser using buffered content (could be…

### PR DESCRIPTION
**Pull request by pmalhaire**
… a socket)

Based on https://github.com/msgpack/msgpack-c/issues/540 
I added an example to the message pack project

### CODE REVIEW

**Comment by pmalhaire** [comment]
`Note :`  
your travis-ci for OSX is broken : https://travis-ci.org/msgpack/msgpack-c/jobs/180026753

Valgrind 3.10.1 which does not support OSX kernel 14.5.0 (Sierra if I remember well) valgrind 3.12.0 has limited Sierra support see http://valgrind.org/downloads/

I guess changing from http://valgrind.org/downloads/valgrind-3.10.1.tar.bz2 to http://valgrind.org/downloads/valgrind-3.12.0.tar.bz2 would make it work.

**Comment by redboltz** [comment]
I  tried valgrind-3.12.0 but got errors that are the same as #527.
@nobu-k, could you test the PR and #527 on your environment?

**Comment by redboltz** [comment]
It seems that macos sierra isn't well supported by valgrind.
https://github.com/msgpack/msgpack-c/issues/527#issuecomment-266263648

I started thinking that I remove valgrind check from macos build.

**Comment by redboltz** [comment]
I disabled valgrind from osx build. When valgrind will support osx, I will add it again.

**Pull request merged**
