### PR TITLE
convert between msgpack and json via cJSON library

### PR DESCRIPTION
**Pull request by ygj6**
- Pack json string to msgpack format data.
`int msgpack_pack_jsonstr(msgpack_packer *pk, const char *jsonstr)`

- Convert msgpack format data to json string.
`int msgpack_object_print_jsonstr(char *buffer, size_t length, const msgpack_object o)`

### CODE REVIEW

**Comment by redboltz** [comment]
It seems that you added not only json example for C but also some convenient functions.
I think that they are nice to have.
I'm not familiar with the word "intact". I've checked it using dictionary and understand it.
Do you have any other candidate words for that ?
If "intact" is the best one, I apply it. (I'm not a native English speaker:)

**Comment by redboltz** [comment]
I think that `msgpack_pack_str_with_body` could be a better name. Because `msgpack_pack_str` is used for packing STR header and `msgpack_pack_str_body` is used for packing STR body. The newly introduced function is both STR header and body. The name `msgpack_pack_str_with_body`  mean that directly.
What do you think?

**Comment by ygj6** [comment]
I have another idea:
```
msgpack_pack_str() => msgpack_pack_str_head()
msgpack_pack_str_body() => msgpack_pack_str_body()
msgpack_pack_str_intact() => msgpack_pack_str()/msgpack_pack_str_easy()/...
```
map, array, ext are the same as str.

**Comment by redboltz** [comment]
If I design the API from the scratch, the following functions are better as you mentioned.
Personally, I don't like `easy` it is too subjective word for me ;) .

```c
msgpack_pack_str() => msgpack_pack_str_head()/msgpack_pack_str_header()
msgpack_pack_str_body() => msgpack_pack_str_body()
msgpack_pack_str_intact() => msgpack_pack_str()
```

However, I want to avoid breaking change because it require code updating to many users.

**Comment by ygj6** [comment]
Indeed, `msgpack_pack_str()` is an old funtion, changing it will cause ABI to be incompatible with previous versions. Maybe we can change it in a major version upgrade in the future.

Now I'll use `msgpack_pack_str_with_body()`.

**Comment by redboltz** [comment]
Thank you for understanding and updating the code.

**Pull request merged**
