### PR TITLE
Add range-based for loop support.

### PR DESCRIPTION
**Pull request by al11090**
Add function "msgpack::begin", "msgpack::end".
We can write code like following.

```cpp11
for (msgpack::object &element : myobject1.via.array) {
    //...
}

for (msgpack::object_kv &kv : myobject2.via.map) {
    // ...
}
```

### CODE REVIEW

**Comment by redboltz** [comment]
Thank you for sending the PR. It looks nice!

After adding tests and [versioning namespace](https://github.com/msgpack/msgpack-c/wiki/cpp_versioning), I will merge it.

**Comment by al11090** [comment]
Thank you for your review.
I added those.

**Comment by redboltz** [comment]
Merged.
I modified a little before I merged it:
https://github.com/msgpack/msgpack-c/commit/ff86d61799d08bb31e0448fcdf6270aa2d5b10dd

```C++
#include <msgpack.hpp>
#include <cassert>

int main() {
    unsigned int i = 42;
    msgpack::object o(i);

    // i is converted to msgpack::object
    assert(o == i);
    assert(i == o);

    assert(o.as<unsigned int>() == i);
    assert(i == o.as<unsigned int>());
}
```
Your comparison using EXPECT_EQ occurs converting constructor.

https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/object.hpp#L403

I think that unsigned int comparison is better.

**Comment by redboltz** [comment]
Hi, @al11090. We are trying to change msgpack-c's license from Apache to Boost. See https://github.com/msgpack/msgpack-c/issues/366 discussion. This PR contains your copyright notice. So we need to get your agreement. If you read this comment, please reply your idea.

**Comment by redboltz** [comment]
現在、ライセンス変更を検討しており、著作権者にコンタクトを取っております。
もし、github通知でこのコメントを確認いただけましたら、私 redboltz@gmail.com に連絡、あるいはここにコメントお願いいたします。

**Pull request closed without merging**
