### PR TITLE
Bindings for Vala

### PR DESCRIPTION
**Pull request by arteymix**
It's almost complete as I expect some feedback about which APIs should be exposed. I also need to test it more thoroughly.

There's some functional tests which could be part of your testsuite I would like to include, but it would require external dependencies like `valac`.

I don't mind updating them over time as I plan to use MessagePack for personal projects, so you can leave me a message before releasing anything new.

### CODE REVIEW

**Comment by redboltz** [comment]
Thank you for sending the PR. Unfortunately. I don't know much about valac. I will study about valac and the PR later. I can't judge which part of the code should be included in the msgpack-c. Please wait a moment.

**Comment by arteymix** [comment]
It's more about the unpacker and zone part that I'm unsure of what should be exposed. Also, maybe other C headers can be useful.

I am reworking the `MessagePack.Union` part to be more convenient for real usages. For instance, the primitive types should not be wrapped in a struct.

**Comment by redboltz** [comment]
I studied a little about vala. https://en.wikipedia.org/wiki/Vala_(programming_language). I think that the PR should not a part of `msgpack-c` but a part of another project such as `msgpack-vala`. And `msgpack-vala` contains `msgpack-c` as a sub project.

> It's more about the unpacker and zone part that I'm unsure of what should be exposed. Also, maybe other C headers can be useful.

Basically, functions and structures that are defined in https://github.com/msgpack/msgpack-c/blob/master/include/msgpack.h are candidate of exposing.

**Comment by arteymix** [comment]
Typically, bindings end up in [nemequ/vala-extra-vapis](https://github.com/nemequ/vala-extra-vapis), but it is not always possible to keep them up-to-date with evolving projects.

I guess I will submit it there and start working on something like `msgpack-glib` the moment I need it.

**Comment by arteymix** [comment]
By the way I just posted a PR for that binding: https://github.com/nemequ/vala-extra-vapis/pull/36

It works really great so I think it could be interesting to add a code example on the main page.

**Pull request closed without merging**
