### PR TITLE
Ported #962 to C++.

### PR DESCRIPTION
**Pull request by redboltz**
Improved alignment calculation logic.

### CODE REVIEW

**Comment by redboltz** [comment]
@kovdan01 Before I release the next version, I'm porting #962 (for C) to C++.

Most of work is done. But I found weird error on the CI.
Only Linux (pattern0) reports compile error
https://github.com/msgpack/msgpack-c/pull/965/checks?check_run_id=3453292555#step:8:156

Defining uintptr_t depends on implementation. It's OK.
https://en.cppreference.com/w/cpp/types/integer

But what is the difference between pattern0 and other patterns ? 

Could you help me if you have time?

**Comment by kovdan01** [comment]
> Could you help me if you have time?

Sure, I'll investigate the problem and write about results.

**Comment by redboltz** [comment]
Thank you!

**Comment by redboltz** [comment]
The compile error is caused by lack of include "cstdint". It has been introduced since C++11. For C++03 (Linux pattern 0 !), "stdint.h" can be used.

**Pull request merged**
