### PR TITLE
reduce boost::context requirement

### PR DESCRIPTION
**Pull request by sharkcz**
Remove the requirement for Boost Context module, it's not used anywhere if I see right.

Tested on Fedora 32 for s390x without the context module, it builds and passes all tests.

### CODE REVIEW

**Comment by redboltz** [comment]
Boost.Context is used at https://github.com/msgpack/msgpack-c/blob/cpp_master/example/x3/CMakeLists.txt#L50

It is a msgpack-c with spirit.x3 example.
Perhaps context requirement should be conditionally added.

**Comment by sharkcz** [comment]
OK, so I was wrong, there is a combination where it's needed (via boost::coroutine). How about  require it only when the X3 parsing is enabled?

**Comment by redboltz** [comment]
It is x3 example. So the condition is `MSGPACK_USE_X3_PARSE=ON` and `MSGPACK_BUILD_EXAMPLES=ON`

**Comment by sharkcz** [comment]
and MSGPACK_DEFAULT_API_VERSION must be greater than 1, updated PR follows

**Comment by redboltz** [comment]
I'm not sure what happens if `FIND_PACKAGE Boost... )` called twice. The expected behavior is that sub directory one inherits the parent directory and adding sub directory components?

**Comment by sharkcz** [comment]
When looking at the generated `build/CMakeCache.txt` I see each module has its own pair of variables (for debug/release build). And looking further I'm pretty sure the modules can be incrementally added (there is `_Boost_COMPONENTS_SEARCHED:INTERNAL=chrono;context;system;timer` set later).

**Comment by sharkcz** [comment]
at least on Linux, not sure why the `appveyor` test fails now

**Comment by redboltz** [comment]
@ygj6 , could you investigate appveyor's error?
The PR doesn't modify appvayor.yml.
Ther error is similar to [the error you fixed](https://ci.appveyor.com/project/redboltz/msgpack-c/builds/33359075/job/mloai5ticktlxk26).

**Comment by redboltz** [comment]
I think that you need to remove context from the following line:

https://github.com/msgpack/msgpack-c/blob/cpp_master/appveyor.yml#L51

The reason is complecated.

cmake fails find boost on old msvc image if I wrote `COMPONENTS ...` , I don't know why.
If `COMPONENTS ...` is removed, cmake worked well.
However it caused error on linux(ubuntu) and mac.

So we replace CMakeLists.txt dynamically on appveyor.

Your PR affects matching pattern.

**Comment by redboltz** [comment]
Find boost with COMPONENTS appears https://github.com/msgpack/msgpack-c/pull/882/files#diff-2f67c712aa887d7c764fd59e64b963d9R2 too.

I guess that it's safe because there is no x3 and example build on appveyor.

**Comment by sharkcz** [comment]
I see, let's try it once more :-)

**Comment by redboltz** [comment]
Looks good to me. Thanks.

**Pull request merged**
