### PR TITLE
Improve CMake package generation

### PR DESCRIPTION
**Pull request by herbrechtsmeier**
At the moment the CMake package config is useless below CMake version 3.0 and should be disabled. Additionally exported targets should be prefixed by a namespace `msgpack::`.

### CODE REVIEW

**Comment by herbrechtsmeier** [comment]
The exported target names `msgpackc*` of the CMake package differ from the package name `msgpack`. Maybe they should be renamed.

**Comment by redboltz** [comment]
It seems that TAB is contained in the PR.
https://github.com/msgpack/msgpack-c/pull/589/files#diff-af3b638bc2a3e6c650974192a53c7291R341

Could you replace them to space?

**Comment by herbrechtsmeier** [comment]
I found a solution for the `export(export)` problem and will update the pull request.

**Comment by herbrechtsmeier** [comment]
@redboltz What is the preferred name for the exported targets which are used by external projects? Should I rename the targets to `msgpack::msgpack` without a `c` at the end?

**Comment by redboltz** [comment]
@herbrechtsmeier , `msgpack::msgpackc` is good.

The C++ part of `msgpack-c` uses the name `msgpack`.
The C part of msgpack-c` uses the name `msgpackc`.

The C++ part is a header only library so it doesn't need exporting.
So exporting functionality is for the C part of `msgpack-c`.
Hence, the name should be `msgpack::msgpackc`.

If I don't understand correctly about exporting functionality, please let me know.

**Comment by herbrechtsmeier** [comment]
@redboltz Even the header only library should export a target. This allows CMake to automatically add the correct include path. This means that we need to export three targets:
- shared c library (msgpackc-shared or msgpack-c-shared)
- static c library (msgpackc-static or msgpack-c-static)
- c++ headers (msgpackc++, msgackcpp, msgpackcxx, msgpack-c++, msgpack-cpp or msgpack-cxx)
Additionally I would add a fourth target with select the correct c library depending on the BUILD_SHARED_LIBS variable (msgpackc or msgpack-c).

You could determine the name. By the way many find modules and projects use a package and namespace name with upper case  letters (example: Threads, Boost and OpenCV).

**Comment by redboltz** [comment]
Hmm...

I think that the namespace name is `MessagePack`.
In the namespace `msgpackc-static`, `msgpackc-shared`, `msgpackc-headers`, and `msgpack-cpp-headers` should be placed.

So

```
MessagePack::msgpackc-static
MessagePack::msgpackc-shared
MessagePack::msgpackc-headers
MessagePack::msgpackc-cpp-headers
```

**Comment by herbrechtsmeier** [comment]
I think the namespace should match with the package name. The namespace is only used to distinguish the exported targets. At the moment the project name is msgpack. The pkg-config file also use the name msgpack.

What should be the use case of the `MessagePack::msgpackc-headers` target?

**Comment by redboltz** [comment]
> What should be the use case of the MessagePack::msgpackc-headers target?

`MessagePack::msgpackc-cpp-headers` might not need.
`MessagePack::msgpackc-headers` is for exporting C and C++ headers.

**Comment by redboltz** [comment]
I'm not sure cmake exporting mechanism.

**Comment by herbrechtsmeier** [comment]
An exported target contains amongst others libraries and headers. It doesn't matter if the target is a real library or header only library. The users only add the exported target to its targets via `target_link_libraries`. This means we need a target for the c library and c++ library. It doesn't matter how the library is implemented.

**Comment by redboltz** [comment]
Thank you for clarification. 
I think that the export name should be `msgpack::msgpack`.
And this exports all features (include paths and linking libraries).

**Comment by redboltz** [comment]
Or respect the existing convention, `Msgpack::msgpack`.
Am I understanding correctly?

**Comment by herbrechtsmeier** [comment]
Do you mean one target for C and C++? This means we always links against the c library even if it isn't used. Additionally the user need to adapt this CMake files if you ever decide to use a real c++ library. I would prefer two main targets:

- `msgpack::msgpack-c`
- `msgpack::msgpack-cpp`

Additionally I would add two target for the different c library types:
- `msgpack::msgpack-c-shared`
- `msgpack::msgpack-c-static`

**Comment by herbrechtsmeier** [comment]
The package name `Msgpack` and `msgpack` is a matter of taste.

**Comment by redboltz** [comment]
Is exporting function corresponding to FindXxx?

For example Boost is https://cmake.org/cmake/help/v3.0/module/FindBoost.html

I mean FindMsgpack.

I think that we can output many variables. And user can choose them. If user needs only C part of msgpack-c, use the variable that is corresponding to C.

Is that wrong?

**Comment by herbrechtsmeier** [comment]
A FindXxx is used if the project don't generate a package configuration. We could do the same in the `msgpack-config.cmake` or `MsgpackConfig.cmake`.

The variables make thinks much more complicated and often used for backward compatibility. You could do the same think and much more with targets.

**Comment by herbrechtsmeier** [comment]
The targets allows users to add Msgpack as a dependency to their libraries. 

CMakeLists.txt
```
find_package(Msgpack)

add_library(testc test.c)
target_link_libraries(testc PUBLIC Msgpack::msgpack-c)

add_library(testcpp test.cpp)
target_link_libraries(testc PUBLIC Msgpack::msgpack-cpp)
```

TestConfig.cmake.in
```
include(CMakeFindDependencyMacro)
find_dependency(Msgpack)
```

**Comment by redboltz** [comment]
@herbrechtsmeier thank you for the description.

I'd like to check I understand correctly.

Now I understand the package namespace and names as follows:

```
Msgpack::msgpack-cpp // contain header files (path?)
Msgpack::msgpack-c-shared // contain header files(path?) and shared library
Msgpack::msgpack-c-static // contain header files(path?) and static library
Msgpack::msgpack-c // contain header files(path?) and both shared library and static library
```

@herbrechtsmeier , could you check it?

**Comment by herbrechtsmeier** [comment]
@redboltz Mostly correct, but `Msgpack::msgpack-c` will be an alias for `Msgpack::msgpack-c-shared` and if not available for `Msgpack::msgpack-c-static`. This allows the user to simple link against the available library.

**Comment by redboltz** [comment]
@herbrechtsmeier , I agree with your packaging policy.

travis-ci and appveyor reported errors. Please fix them.

I experienced similar appveyor errors. appveyor support said that replace `\\` with `/` solves the problem as follows:

```
BOOST_ROOT="C:\\..."
```

```
BOOST_ROOT="C:/..."
```

**Comment by herbrechtsmeier** [comment]
Please don’t apply this PR until I post a summary. The PR is still a work in progress and is missing some more rework and additional CI tests.

**Comment by redboltz** [comment]
@herbrechtsmeier , OK, I will wait. Please let me know if the work is finished :)

**Comment by herbrechtsmeier** [comment]
What is the desired behaviour for the Boost support? Should the define `MSGPACK_USE_BOOST` be set if the Boost library was available during msgpack build or if the Boost library is available during user project build?

**Comment by herbrechtsmeier** [comment]
@redboltz Are you sure that the boost tests and examples are working in the current master?

**Comment by redboltz** [comment]
@herbrechtsmeier , boost::string_view and boost::string_ref conflict some version of boost. I experienced it on Boost 1.62.0. AFAIK, the problem is fixed on 1.63.0 or later.
So I use it on travis-ci https://github.com/msgpack/msgpack-c/blob/master/.travis.yml#L30

I don't check all CI results but I found Boost 1.62.0 seems to be used https://travis-ci.org/msgpack/msgpack-c/jobs/229289379#L128

**Comment by redboltz** [comment]
> What is the desired behaviour for the Boost support? Should the define MSGPACK_USE_BOOST be set if the Boost library was available during msgpack build or if the Boost library is available during user project build?

MSGPACK_USE_BOOST is C++ compiler flag. See https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_configure#msgpack_use_boost-since-120

Define or NOT define MSGPACK_USE_BOOST is decided by user.
In cmake, for C++ it is only for building tests and examples, if cmake flag MSGPACK_BOOST is defined, then the compiler flag MSGPACK_USE_BOOST is defined.
https://github.com/msgpack/msgpack-c/blob/master/CMakeLists.txt#L93

If MSGPACK_BOOST is defined, boost test enables the boost part of tests.
https://github.com/msgpack/msgpack-c/blob/master/test/CMakeLists.txt#L42

In each test files, MSGPACK_USE_BOOST is checked too.
https://github.com/msgpack/msgpack-c/blob/master/test/boost_fusion.cpp#L12

It might be redundant, but not harmful.

**Comment by herbrechtsmeier** [comment]
@redboltz I have also test boost 1.63 and it returns the same error. Furthermore Boost 1.62 works on my computer. I will rework the CI builds in an other PR.

**Comment by redboltz** [comment]
I just started rebuild master 88338195c0733b9e0cadcab7253bf56000e18de9 on travis-ci and appveyor.

* master 
  * travis-ci
    * https://travis-ci.org/msgpack/msgpack-c/builds/225921688
  * appveyor
    * https://ci.appveyor.com/project/redboltz/msgpack-c/build/2.1.0.470

**Comment by herbrechtsmeier** [comment]
CMake could not find Boost on master:
```
Could NOT find Boost
```

**Comment by redboltz** [comment]
Both passed.

**Comment by herbrechtsmeier** [comment]
The CI builds only work because the build script manually sets the boost include path and bypass the `FindBoost` module.

**Comment by redboltz** [comment]
I don't have a solution. Consult cmake support, please.

**Comment by redboltz** [comment]
@herbrechtsmeier , I merged #591.
 
I'm not sure #591 is the fix that relates to this PR. But I tried to merge this PR with the up-to-date master.

Here is merged branch. https://github.com/redboltz/msgpack-c/tree/herbrechtsmeier-config
Then I got the following errors on CI.
https://travis-ci.org/redboltz/msgpack-c/builds/237064317
https://ci.appveyor.com/project/redboltz/msgpack-c-pnitn/build/2.1.0.655

**Comment by herbrechtsmeier** [comment]
@redboltz I'm still working on this PR.

**Comment by redboltz** [comment]
@herbrechtsmeier , thank you for the comment. I understand the situation :)

**Comment by dennisklein** [comment]
@herbrechtsmeier @redboltz Is anyone still working on this? If not, I would like to pick it up and get it merged and released.

Specifically, I would like to have a C++ header-only target exported and for packaging purposes in Fedora we need a build switch to turn off building the static library (see https://bugzilla.redhat.com/show_bug.cgi?id=1596164)

**Comment by redboltz** [comment]
@dennisklein , I do nothing about the PR. But if your goal is remove static-library on build, the issue is reported by #703 and fixed by #713 .

**Comment by dennisklein** [comment]
Great, thank you very much. That should help with the packaging problem. I'll have a look.

**Comment by redboltz** [comment]
@dennisklein , you can do that as follows:

```
cmake -DMSGPACK_ENABLE_STATIC=OFF -DBUILD_SHARED_LIBS=ON ..
```

If it is OK, I will release it as the version 3.1.0.

**Comment by dennisklein** [comment]
I found a small bug, in [CMakeLists.txt#L305-L311](https://github.com/msgpack/msgpack-c/blob/3aaadb9b12261ec163735dc09a44689f324b48a9/CMakeLists.txt#L305-L311). I believe, it should be

```cmake
IF (BUILD_SHARED_LIBS OR MSGPACK_ENABLE_SHARED)
    SET (MSGPACK_INSTALLTARGETS msgpackc)
ENDIF ()

IF (MSGPACK_ENABLE_STATIC)
    LIST (APPEND MSGPACK_INSTALLTARGETS msgpackc-static)
ENDIF ()
```

**Comment by dennisklein** [comment]
Actually, you always have a `msgpackc` target, so it should be:

```cmake
SET (MSGPACK_INSTALLTARGETS msgpackc)

IF (MSGPACK_ENABLE_STATIC)
    LIST (APPEND MSGPACK_INSTALLTARGETS msgpackc-static)
ENDIF ()
```

---

Another minor thing is that I get (CMake 3.11.2)

```
~/projects/msgpack-c/build $ cmake -GNinja -DMSGPACK_ENABLE_STATIC=OFF -DBUILD_SHARED_LIBS=ON ..
CMake Deprecation Warning at CMakeLists.txt:158 (MESSAGE):
  MSGPACK_ENABLE_SHARED is deprecated.  Use BUILD_SHARED_LIBS instead.


-- Configuring done
-- Generating done
-- Build files have been written to: /home/dklein/projects/msgpack-c/build
```

**Comment by dennisklein** [comment]
Just for completeness, there is still a logic error with the two shared library switches:

```
~/projects/msgpack-c/build $ cmake -GNinja -DBUILD_SHARED_LIBS=OFF ..
~/projects/msgpack-c/build $ ninja -t query msgpackc                                            
msgpackc:
  input: phony
    libmsgpackc.so
  outputs:
~/projects/msgpack-c/build $ ninja -t query msgpackc-static
msgpackc-static:
  input: phony
    libmsgpackc.a
  outputs:
```

As you can see, even though I switched off building of shared libs, it is still built.

**Comment by redboltz** [comment]
I've tested and got the following results. It is different from yours. Do you remove all files and directories on build directory when you change the switches?

There are 3 switches. 

|Name|Default|Effects|
|---|---|---|
|MSGPACK_ENABLE_SHARED|ON|Deprecated. Only for keeping the same behavior as the older release.|
|MSGPACK_ENABLE_STATIC|ON|Build static library|
|BUILD_SHARED_LIBS|OFF|Cmake common flag.|

If ether MSGPACK_ENABLE_SHARED or BUILD_SHARED_LIBS is ON, shared library is built.
If both of them are OFF, shared library is not built.

Here is my test results.

|MSGPACK_ENABLE_STATIC|MSGPACK_ENABLE_SHARED|BUILD_SHARED_LIBS|Result|
|---|---|---|---|
|OFF|OFF|OFF|Error as expected *1|
|OFF|OFF|ON|libmsgpackc.so is created|
|OFF|ON|OFF|Warning *2. libmsgpackc.so is created *3|
|OFF|ON|ON|Warning *2. libmsgpackc.so is created *3|
|ON|OFF|OFF|libmsgpackc.a is created|
|ON|OFF|ON|libmsgpackc.a, libmsgpackc.so, libmsgpackc.so.2, and libmsgpackc.so.2.0.0 are created|
|ON|ON|OFF|Warning *2. libmsgpackc.a, libmsgpackc.so, libmsgpackc.so.2, and libmsgpackc.so.2.0.0 are created|
|ON|ON|ON|Warning *2. libmsgpackc.a, libmsgpackc.so, libmsgpackc.so.2, and libmsgpackc.so.2.0.0 are created|

*1
```
CMake Error at CMakeLists.txt:386 (EXPORT):
  EXPORT Export set "msgpack-targets" not found.
```

*2
```
CMake Deprecation Warning at CMakeLists.txt:158 (MESSAGE):
  MSGPACK_ENABLE_SHARED is deprecated.  Use BUILD_SHARED_LIBS instead.
```

*3
```
libmsgpackc.so, libmsgpackc.so.2, and libmsgpackc.so.2.0.0 should be created.
```

I use

```
rm -rf build
mkdir build
cd build
cmake -Doptions_above ..
make
```

I will fix *3 issue.

**Comment by redboltz** [comment]
Also I will fix https://github.com/msgpack/msgpack-c/pull/589#issuecomment-411992898.

**Comment by dennisklein** [comment]
I will verify everything on monday, currently I am on a family wedding. If the 3.1 release can wait I would like to see a header only target exported too. The code st basically already in this PR, I could extract the relevant parts.

**Comment by redboltz** [comment]
No problem, I will wait your check:) Enjoy the family wedding!

**Comment by redboltz** [comment]
#717 added two fixes.

**Comment by redboltz** [comment]
After #717 merged, the result is:

|MSGPACK_ENABLE_STATIC|MSGPACK_ENABLE_SHARED|BUILD_SHARED_LIBS|Result|
|---|---|---|---|
|OFF|OFF|OFF|Error as expected *1|
|OFF|OFF|ON|libmsgpackc.so, libmsgpackc.so.2, and libmsgpackc.so.2.0.0 are created|
|OFF|ON|OFF|Warning *2. libmsgpackc.so, libmsgpackc.so.2, and libmsgpackc.so.2.0.0 are created|
|OFF|ON|ON|Warning *2. libmsgpackc.so, libmsgpackc.so.2, and libmsgpackc.so.2.0.0 are created|
|ON|OFF|OFF|libmsgpackc.a is created|
|ON|OFF|ON|libmsgpackc.a, libmsgpackc.so, libmsgpackc.so.2, and libmsgpackc.so.2.0.0 are created|
|ON|ON|OFF|Warning *2. libmsgpackc.a, libmsgpackc.so, libmsgpackc.so.2, and libmsgpackc.so.2.0.0 are created|
|ON|ON|ON|Warning *2. libmsgpackc.a, libmsgpackc.so, libmsgpackc.so.2, and libmsgpackc.so.2.0.0 are created|

*1
```
CMake Error at CMakeLists.txt:386 (EXPORT):
  EXPORT Export set "msgpack-targets" not found.
```

*2
```
CMake Deprecation Warning at CMakeLists.txt:158 (MESSAGE):
  MSGPACK_ENABLE_SHARED is deprecated.  Use BUILD_SHARED_LIBS instead.
```

All results are expected. 

If you want to create only static-library, set `MSGPACK_ENABLE_STATIC=ON` (default) and `MSGPACK_ENABLE_SHARED=OFF`.

If you want to create only shared-library, set `MSGPACK_ENABLE_STATIC=OFF` and `BULD_SHARED_LIBS=ON` (recommended).

If you want to create both, set `MSGPACK_ENABLE_STATIC=ON` (default) and `BULD_SHARED_LIBS=ON` (recommended).

You can omit `(default)` setting.

To keep compatibility `MSGPACK_ENABLE_SHARED=ON` by default. This switch is marked as deprecated. It will be removed in the future release.

**Comment by dennisklein** [comment]
@redboltz Thx! The changes you have made, work for me. Also, I proposed #721 which adds an interface library target for the C++ header-only library.

**Comment by herbrechtsmeier** [comment]
@redboltz Hi, why is *1 an expected behaviour? Normally BUILD_SHARED_LIBS is used to build shared (ON) or static (OFF) libraries. In my patch I build both libraries only if BUILD_SHARED_LIBS is undefined and otherwise build only the requested version.

**Comment by redboltz** [comment]
@herbrechtsmeier ,
> @redboltz Hi, why is *1 an expected behaviour? Normally BUILD_SHARED_LIBS is used to build shared (ON) or static (OFF) libraries. 

I didn't know `BUILD_SHARED_LIBS` means that. I thought that `BUILD_SHARED_LIBS` is for simple building shared-library switch and not affects for static-library building. I tried to find `BUILD_STATIC_LIBS` but I didn't found it. Now I understand why.

It seems that there is no official way to build both static and shared library.

> In my patch I build both libraries only if BUILD_SHARED_LIBS is undefined and otherwise build only the requested version.

I think that your approach is good. It keeps cmake's natulal `BUILD_SHARED_LIBS` meaning. 

I will add minimal change for `BUILD_SHARED_LIBS`.

**Comment by redboltz** [comment]
> I will add minimal change for BUILD_SHARED_LIBS.

#722 will fix the issue.

**Comment by ChisholmKyle** [comment]
I'm getting a configure error when using `find_package(msgpack)` #801 and I think it might have to do with not having a global namespace `msgpack::`. Would this PR fix it? Or is there something else going on?

**Comment by redboltz** [comment]
@ChisholmKyle , there is no other PR.
This PR is pretty old, CI isn't passed and there are many conflicts. I think that creating a new PR to fix #801 is good.

**Comment by ChisholmKyle** [comment]
I added the Msgpack:: namespace to CMake exports in PR #802

**Pull request closed without merging**
