### PR TITLE
Proposal for specifying MSGPACK_BUILD_EXAMPLES option with CMakefile.txt.

### PR DESCRIPTION
**Pull request by awrznc**
Hi,
I want to contribute to this great project.

When I was using this project, I thought it would be even more useful if the way to specify the build options could be more flexible.
So, I made it possible to specify the `MSGPACK_BUILD_EXAMPLES` option in CMakeLists.txt.

Currently, if you want to disable the build of example, you need to pass the option to the command as follows.

```bash
cmake -DMSGPACK_BUILD_EXAMPLES ..
```

This is also the case when you use add_subdirectory in cmake.

```cmake
cmake_minimum_required(VERSION 3.19)

# msgpack
add_subdirectory(msgpack-c)
include_directories(${msgpack_SOURCE_DIR}/include)

# main build
add_executable(main_app main.cpp)
```

I think it's cool to manipulate the build behavior with options to the command, but it can be a bit verbose when introducing it to a project.

So I thought it would be useful if the `MSGPACK_BUILD_EXAMPLES` option could be specified in the project's CMakeLists.txt file.
An example is shown below.

```diff
cmake_minimum_required(VERSION 3.19)

# msgpack
+ set(MSGPACK_BUILD_EXAMPLES OFF)
add_subdirectory(msgpack-c)
include_directories(${msgpack_SOURCE_DIR}/include)

# main build
add_executable(main_app main.cpp)
```

Now the members of the project can develop without worrying about the cmake options.

I would be happy to get some feedback on this fix.
If there is a problem, I will close it. (I'm sorry if I missed any important sentences.)

### CODE REVIEW

**Comment by redboltz** [comment]
```
cmake -DMSGPACK_BUILD_EXAMPLES ..
```

It is quite misleading even if it works.

```
cmake -DMSGPACK_BUILD_EXAMPLES=OFF ..
```

It is the right way. 

By default, building examples is **expected** behavior. It is the project decision.
There is a way to disable to make example if the builder want to do.

The is no problem.

Other options are also defined the same way. 

See

```cmake
SET (Boost_USE_MULTITHREADED      ON)
```

If the builder want to disable boost multithread, then the builder can do as follows:

```
cmake -DBoost_USE_MULTITHREADED=OFF ..
```

It is unified way.

**Comment by awrznc** [comment]
@redboltz 
Thank you for your quick reply.

> It is quite misleading even if it works.

I'm sorry, I made a mistake in the cmake description of the pull request.
Your description is the correct one.

```bash
cmake -DMSGPACK_BUILD_EXAMPLES=OFF ..
```


> By default, building examples is expected behavior. It is the project decision.
>  There is a way to disable to make example if the builder want to do.

In other words, is the following meaning correct?
"If you want to specify an option, please use the command. Other methods are not allowed by the megpack-c project policy."

**Comment by redboltz** [comment]
Improvement ideas are very welcome.
I couldn't find any benefit in the PR. In addition `MSGPACK_BUILD_EXAMPLES STREQUAL "OFF"` is not natural way on cmake for me.
Also I don't understand why MSGPACK_BUILD_EXAMPLES is the only target. There are many similar options. Applying the same approach for all other options is terrible for me. On of a big disadvantage is CMakeLists.txt would become messy.

**Comment by awrznc** [comment]
> In addition `MSGPACK_BUILD_EXAMPLES STREQUAL "OFF"` is not natural way on cmake for me.

The reason for this gap may be my limited knowledge of CMake.
I would like to respect your opinion.

> Also I don't understand why MSGPACK_BUILD_EXAMPLES is the only target.

There was no deeper meaning there. If there were any concerns, we planned to address them additionally.
And my consideration was lacking. 

After listening to your opinion, I feel that this PR does not have enough merit to break the consistency that we have had.
Also, while doing research for this comment, I found that I could do something similar with the following statement.

```cmake
set(MSGPACK_BUILD_EXAMPLES OFF CACHE BOOL "Xxx")
```

Based on the above events, I would like to close this PR.
Thank you very much for your kind attention.

I hope this project will be used by many more developers in the future :)

**Pull request closed without merging**
