### PR TITLE
Fix compilation error when `std::variant` has the same types

### PR DESCRIPTION
**Pull request by uyha**

### CODE REVIEW

**Comment by uyha** [comment]
@redboltz could you have a look and create a minor release if everything is good? I need this for my project.

**Comment by redboltz** [comment]
Thank you for sending the PR. 
I didn't know about in_place_index_t. It can clarify the index!
I will merge it and will release the updated version ASAP.

Just my curious, when do you use `std::variant` that contains the same types?

**Comment by uyha** [comment]
I have a very heavy template code base and there's basically a type list that is a list of events. For example,
```cpp
using Events = TypeList<Event1, Event2, Event3>;
```
This list will be used as common source for events coming in and out. Sometimes, the event list isn't used as is because the receiving end doesn't accept an "event", but some modified version of those "event"s and a modified version can be 
```cpp
template<typename>
using TimePoint = std::chrono::system_clock::time_point_t;
```
So a receiving end can sometimes accept a `std::variant<Event1, Event2, Event3>` and sometimes it can accept a `std::variant<TimePoint<Event1>, TimePoint<Event2>, TimePoint<Event3>>` (which is a variant having same types).

(I'm not sure if I make it clearer or not, if you want to know more, please let me know)

**Comment by redboltz** [comment]
Thank you for the comment. I understand your situation. Good to know :)

**Pull request merged**
