### PR TITLE
Change CMake package name of C library to msgpackc

### PR DESCRIPTION
**Pull request by traversaro**
Change the CMake package name to msgpackc, as requested in https://github.com/msgpack/msgpack-c/issues/1043#issuecomment-1372169699 . After this change, to find the C library in the system, it is necessary to call:
~~~cmake
find_package(msgpackc REQUIRED)
~~~
instead of the previously used:
~~~cmake
find_package(msgpack REQUIRED)
~~~

Fix https://github.com/msgpack/msgpack-c/issues/1043 .

### CODE REVIEW

**Comment by traversaro** [comment]
AppVeyor build is failing with:
~~~
-- Build files have been written to: C:/projects/msgpack-c/googletest-release-1.7.0/build
cmake --build . --config Release
Microsoft (R) Build Engine version 4.8.3761.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.
  Checking Build System
  Building Custom Rule C:/projects/msgpack-c/googletest-release-1.7.0/CMakeLists.txt
  gtest-all.cc
     Creating library C:/projects/msgpack-c/googletest-release-1.7.0/build/Release/gtest.lib and object C:/projects/msgpack-c/googletest-release-1.7.0/build/Release/gtest.exp
  gtest.vcxproj -> C:\projects\msgpack-c\googletest-release-1.7.0\build\Release\gtest.dll
  Building Custom Rule C:/projects/msgpack-c/googletest-release-1.7.0/CMakeLists.txt
  gtest_main.cc
     Creating library C:/projects/msgpack-c/googletest-release-1.7.0/build/Release/gtest_main.lib and object C:/projects/msgpack-c/googletest-release-1.7.0/build/Release/gtest_main.exp
  gtest_main.vcxproj -> C:\projects\msgpack-c\googletest-release-1.7.0\build\Release\gtest_main.dll
  Building Custom Rule C:/projects/msgpack-c/googletest-release-1.7.0/CMakeLists.txt
cd ..
cd ..
appveyor DownloadFile http://zlib.net/zlib-1.2.12.tar.gz -FileName zlib-1.2.12.tar.gz
Error downloading remote file: One or more errors occurred.
Inner Exception: Remote server returned 404: Not Found
~~~

That does not seem related to this PR.

**Comment by redboltz** [comment]
I guess that you need to update zlib on appveyor.

https://github.com/msgpack/msgpack-c/blob/c_master/appveyor.yml#L25
And other lines.

The current version is zlib 1.2.13

**Comment by redboltz** [comment]
Still 1.2.12 code is remained in appveyor.yml. Please search "1.2.12" and replace them.

**Comment by traversaro** [comment]
The CI is green. The only job that failed is " CI / linux (5) (pull_request) Failing after 1m ", but that is an error independent from the PR, and will probably go away if you restart the job (see https://github.com/actions/runner-images/issues/675).

**Comment by redboltz** [comment]
Thanks, I restarted CI and finally got all green. I will merge it.

**Pull request merged**
