### PR TITLE
Added std::reference_wrapper packing and making object and object_wit…

### LINKED ISSUE #370: would be nice if msgpack can pack std::reference_wrapper
msppack packs std::tuple<std::reference_wrapper<T>> but doesn't pack std::vector<std::reference_wrapper<T>>, or just std::reference_wrapper<T>

### PR DESCRIPTION
**Pull request by redboltz**
…h_zone support.

Fixed #370.

### CODE REVIEW

**Comment by redboltz** [comment]
@jpetso , see https://github.com/msgpack/msgpack-c/issues/370#issuecomment-146745907

**Comment by redboltz** [comment]
Aha, you mean overwrite referance object. I will consider that.

**Comment by redboltz** [comment]
I added a convert adaptor. @jpetso, thank you for the review.

**Comment by jpetso** [comment]
Looks excellent to me! Thank you for considering my comment (and sorry about the unclear phrasing, your second commit is what I meant).

**Pull request merged**
