### PR TITLE
Add msvc project back

### PR DESCRIPTION
**Pull request by aberaud**
Hi,
Just noticed Autotools and MSVC support was dropped.
We use cmake already on Linux and OSX so dropping Autotools is fine for us,
but MSVC is still useful and needed to build natively on Windows.

It makes sense to drop autotools, but I don't see the point to remove native MSVC support.

### CODE REVIEW

**Comment by redboltz** [comment]
@aberaud , I commented https://github.com/msgpack/msgpack-c/issues/469#issuecomment-224437378
msgpack_vc8.sln and msgpack_vc8.vcproj are replaced by cmake.

**Comment by redboltz** [comment]
@aberaud, I will close the PR if you have no comments.

**Comment by aberaud** [comment]
@redboltz
Thanks for your reply,
We use msgpack in a complex project and apparently cmake generated projects have some issues.
Could you consider having native project files back ? It's not that big

**Comment by redboltz** [comment]
@aberaud 

> We use msgpack in a complex project and apparently cmake generated projects have some issues.

If you have a problem using cmake with MSVC, please report the issue. We are ready to solve the problem.

> Could you consider having native project files back ? It's not that big

Ok, I understand your situation, so I merge the PR :)

However, it is out of out support. It is for VS 2008, pretty old. MS provide upgrade mechanism to up to date version of MSVC, so far. However, there is no guaranty providing the mechanism in the future.

I recommend to migrate cmake.

Anyway I merge the PR.

**Pull request merged**
