### PR TITLE
update boost predef and preprocessor from 1.61.0 to 1.68.0

### LINKED ISSUE #728: add support for aarch64 windows
Windows now runs on 64-bit ARM processors, and it seems straightforward enough to add this support alongside the ARM Windows support.

I think I can probably do this myself, but I'm unclear on the best way to go about doing it.  I see `__AARCH64EL__` preprocessor macros for testing endianness, for instance, but no `aarch64.h` header for architecture-specific support.  What's the recommended best way to add this support?

### PR DESCRIPTION
**Pull request by froydnj**
...via `git submodule foreach git pull origin boost-1.68.0` and initializing cmake.

Fixes #728.

### CODE REVIEW

**Comment by redboltz** [comment]
@froydnj ,thank you for sending the PR. It seems that appveyor build is error. So I updated appveyor's boost and merged it by command line.

The PR have already been merged but on web UI still open. I'm looking for how to update the state to merged.

**Comment by redboltz** [comment]
> The PR have already been merged but on web UI still open. I'm looking for how to update the state to merged.

It happened twice. The last case, I updated the status to close. But it is not good. So I asked to 
https://github.com/contact and waiting the response now.

**Comment by froydnj** [comment]
> @froydnj ,thank you for sending the PR. It seems that appveyor build is error. So I updated appveyor's boost and merged it by command line.

Thank you!  I see 7fed49e6fef8bd117da60bfe566b672fc64ce6ea updating appveyor's boost, but I don't see the changes from this issue.  Did you back out the changes while waiting on github support?

**Comment by redboltz** [comment]
I just checked it. I will try to merge it from web-ui.

**Comment by froydnj** [comment]
Thank you for your help fixing the issue!

**Pull request merged**
