### PR TITLE
cmake: Respect --prefix for headers during cmake --install

### PR DESCRIPTION
**Pull request by ericvw**
Removing CMAKE_INSTALL_PREFIX allows for `cmake --install <build-dir> --prefix=<installation-prefix>` to install headers at `<installation-prefix>/include` at install time.

When CMAKE_INSTALL_PREFIX is present in `INSTALL()`, it is hard-coded during configuration (e.g., `cmake -S .`), which disallows it from being set at install time.

Closes: #782

### CODE REVIEW

**Comment by redboltz** [comment]
It seems that the CI (Linux) doesn't start. I think that it is caused by ubuntu18.04 end of support. And your PR is the first one after that.

I guess that the following line should be updated to `ubuntu-latest` or `ubuntu-20.04`. Could you update it in your PR ?
https://github.com/msgpack/msgpack-c/blob/8b57d2caf98003154c4873c7887347669435ca9f/.github/workflows/gha.yml#L69

**Comment by ericvw** [comment]
> I guess that the following line should be updated to `ubuntu-latest` or `ubuntu-20.04`. Could you update it in your PR ?

Sure. Which one do you prefer?

**Comment by ericvw** [comment]
I went with `ubuntu-latest` to be aligned with `macos-latest`.

**Comment by ericvw** [comment]
There is more work involved in updating Linux CI. I will work on that in a separate PR as it is becoming more involved.

**Comment by ericvw** [comment]
I created #1061 to get Linux CI updated…

**Comment by ericvw** [comment]
@redboltz, I rebased this PR against the latest `c_master` branch.

**Comment by redboltz** [comment]
Thank you! merged.

**Pull request merged**
