### PR TITLE
Added a clone function for msgpack::object.

### PR DESCRIPTION
**Pull request by redboltz**
The function prepares zone's chunk that has minimal size to deep copy.

### CODE REVIEW

**Comment by redboltz** [comment]
This PR passed travis-ci. I don't know why travis-ci process is NOT automatically started. Perhaps I removed #287 quickly.

Here is the result of travis-ci. It is the same as this PR.
https://travis-ci.org/redboltz/msgpack-c/builds/63349642

**Comment by jpetso** [comment]
Why does msgpack::move() break const-correctness? If I pass a msgpack::object to a function that takes a `const msgpack::object&`, I should be able to assume that the object is not going to be modified? In C++11 std::move() does not break const-correctness and if you try to std::move a const object, it simply degrades to a copy of that object. std::move only makes a difference on references that are already non-const.

I suggest that msgpack should respect this contract and never move, but only copy out of const objects. It might be that all current operations on const-ref objects currently do a deep copy anyway, but it would be nice if the headers didn't indicate that they might break that contract.

It also seems to me that whenever deep copy is involved, there's no reason to involve msgpack::move() at all? I would feel comfortable if msgpack::move() were a no-op on C++03 so objects always get deep-copied, and C++11 provides a move constructor for msgpack::object so it can perform a shallow copy (and setting source object to nil) as an optimization.

**Comment by redboltz** [comment]
@jpetso , thank you for reviewing. It's very helpful.

The goal of the msgpack::move() is to provide the same interface for C++03 and C++11. However, msgpack::unique_ptr is implemented as std::auto_ptr in C++03. Due to the difference between std::unique_ptr on C++11 and std::auto_ptr on C++03, I needed to write the #if defined(MSGPACK_USE_CPP03) conditional macros.

I agree with you that my design of the PR is poor. I wanted to use const_cast to implement the following code:
```C++
object_handle foo();
object_handle h = foo();
```

and to make matters worse, I modified the C++03 version of msgpack::move().

The reason of the poor design was that I didn't know how std::auto_ptr_ref works.
http://www.cplusplus.com/reference/memory/auto_ptr_ref/

I believe that I understand the design pattern using xxx_ref. When I implement the type that contains auto_ptr such as object_handle, I need to implement object_handle_ref in the same mannar as auto_ptr_ref.

http://melpon.org/wandbox/permlink/kXWggSOhXOFUYTkv

Then, const_cast is no longer required.

I will update my PR.

**Comment by redboltz** [comment]
Updated. @jpetso, I believe that all problems that you pointed out are fixed. Could you check it?

**Comment by jpetso** [comment]
I'm too tired to look right now, will check tomorrow in the morning (Toronto time). Thanks for taking my input, I hope I can provide useful feedback.

**Comment by redboltz** [comment]
Thanks. Take a rest:) I look forward to your feedback tomorrow.

**Comment by jpetso** [comment]
I like it, thanks for addressing my concerns. No objections for getting it merged.

**Comment by redboltz** [comment]
Thank you for the review!

**Comment by redboltz** [comment]
I got a comment from @nobu-k.
This PR will break the ABI. Most of implementation make the same object layout between the original unpacked and object_handle. unpacked became the typedef object_handle.
object_handle is not a POD. So, there is no guaranty to preserve the layout. 

I separated object_handle from unpacked. And provided the conversion operators and constructors.
https://github.com/redboltz/msgpack-c/commit/f75da23e1d4da3cbe6723e32b92df51584045fae

However, this approach adds one conversion layer. So the following code cannot compile in C++03.
```C++
msgpack::object_handle oh = msgpack::unpack(buf, size); // error
msgpack::object_handle oh(msgpack::unpack(buf, size));  // ok
```

The following code cannot compile too.
```C++
msgpack::object_handle oh;
msgpack::unpack(oh, buf, size); // the 1st parameter is unpacked&
```

I think that unpacked and object_handle should be the same type. A possible solution is 
```C++
typedef unpacked object_handler;
```

But I think that the object_handler is more basic type than unpacked.
I'm looking for a better solution.

**Comment by redboltz** [comment]
I will check https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html later.

**Comment by jpetso** [comment]
So, `unpacked` and `object_handle` have the same member variables, so they convey the same information. Since you want to preserve the original declaration with the `unpacked` name, and have already decided to implement an `unpacked_ref` similar to the `object_handle_ref` from further above, would it be possible to just typedef `object_handle` to `unpacked` (or wrap an `unpacked` in `object_handle`) rather than the other way around? This wouldn't be quite as clean but it seems to me that essentially you'd end up with the same functionality.

I'm also interested whether the move to a header-only library would have had any effect on binary compatibility guarantees.

**Comment by redboltz** [comment]
> I'm also interested whether the move to a header-only library would have had any effect on binary compatibility guarantees.

@nobu-k pointed out that the following case:

1. userlib.cpp includes msgpack.hpp <old version>
1. libuserlib.a is created from step1. It has interfaces using msgpack-c, e.g. A reference to msgpack::unpacked.
1. msgpack-c is updated.
1. client.cpp includes msgpack.hpp <new version>
1. client.cpp links to libuserlib.a. client.cpp passes msgpack::unpacked to libuserlib.a. At this point, ABI compatibility is required.

In my opinion, just rebuild libuserlib.a is a solution, but according to @nobu-k, it is sometimes difficult and he has such projects.
So we try keeping ABI compatibility in msgpack-c, and it would break when major updating.

I know the similar case. std::list::size() needs to return the number of element in O(1) since C++11. Some implementation, maybe g++, was using O(N) algorithm. They added a size member variable, then API compatibility is lost.

**Comment by redboltz** [comment]
I've read https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html and http://mentorembedded.github.io/cxx-abi/abi.html

unpacked and object_handle are non POD because that has unique_ptr/auto_ptr.
http://mentorembedded.github.io/cxx-abi/abi.html#class-types

2 If D is not an empty base class or D is a data member:

Start at offset dsize(C), incremented if necessary for alignment to nvalign(D) for base classes or to align(D) for data members. Place D at this offset unless doing so would result in two components (direct or indirect) of the same type having the same offset. If such a component type conflict occurs, increment the candidate offset by nvalign(D) for base classes or by align(D) for data members and try again, repeating until success occurs (which will occur no later than sizeof(C) rounded up to the required alignment).

If D is a base class, this step allocates only its non-virtual part, i.e. excluding any direct or indirect virtual bases.

If D is a base class, update sizeof(C) to max (sizeof(C), offset(D)+nvsize(D)). Otherwise, if D is a data member, update sizeof(C) to max (sizeof(C), offset(D)+sizeof(D)).

If D is a base class (not empty in this case), update dsize(C) to offset(D)+nvsize(D), and align(C) to max (align(C), nvalign(D)). If D is a data member, update dsize(C) to offset(D)+sizeof(D), align(C) to max (align(C), align(D)).


I believe that renaming from unpacked to object_handle, then add member functions and the object_handle_ref nested class, finally add the following typedef is safe on the Itanium ABI.
```C++
typedef object_handle unpacked;
```

I don't have much time to check other ABIs. However, the following assumption is reasonable:
If the class unpacked and object_handle have the same member variables and the same order, then the memory layout is the same. Of course, the compiler setting should be the same.

@nobu-k, if you have against opinion, please let me know. Otherwise, I will merge the PR without the last commit https://github.com/redboltz/msgpack-c/commit/f75da23e1d4da3cbe6723e32b92df51584045fae

**Comment by nobu-k** [comment]
No, I don't have any opposition. I wasn't just confident enough if the typedef approach would work correctly. In terms of their memory layouts, I have the same opinion. My main worry was that I wasn't sure what would happen if I built an application with two shared libraries which had been compiled with different versions of msgpack-c. In this case, however, I *guess* it'd work fine at least with gcc because both versions have the same implementation (i.e. non-inline functions having the same behavior with different type names) and the memory layouts of object_handle and unpacked are same.

**Comment by redboltz** [comment]
@nobu-k , thank you for the comment. I updated the PR. Now, unpacked is the typedef of the object_handle. I will merge it.

**Pull request merged**
