### PR TITLE
Support for complex type

### PR DESCRIPTION
**Pull request by pfeatherstone**

### CODE REVIEW

**Comment by redboltz** [comment]
Thank you for sending the PR.
Could you add test for the PR to https://github.com/msgpack/msgpack-c/blob/master/test/msgpack_cpp11.cpp ?

**Comment by pfeatherstone** [comment]
> Thank you for sending the PR.
> Could you add test for the PR to https://github.com/msgpack/msgpack-c/blob/master/test/msgpack_cpp11.cpp ?

I've added a couple of tests. I don't know how many you want but they pass.

**Comment by redboltz** [comment]
I merged #860. Now CI issue has been solved.
@pfeatherstone , could you rebase your PR from updated master and then force push it ?

I will add comment about how much test is required. Please wait a moment about that.

**Comment by pfeatherstone** [comment]
In windows test (2) it fails on test 31 with error :
Unable to find executable: msgpack_cpp11

**Comment by pfeatherstone** [comment]
Is this another CI config issue in windows ?

**Comment by redboltz** [comment]
https://github.com/msgpack/msgpack-c/pull/859/checks?check_run_id=592575691#step:5:145

Is seems that it is caused by M_PI. Please fix it.
msgpack-c supports multiple platform multiple versions. Some of platform doesn't have features you expect or include file is different. 

It is another topic but you merged master to your PR. Instead of do that, please **rebase** you PR  from updated master. In addition, please clean up your commits.

**Comment by pfeatherstone** [comment]
> https://github.com/msgpack/msgpack-c/pull/859/checks?check_run_id=592575691#step:5:145
> 
> Is seems that it is caused by M_PI. Please fix it.
> msgpack-c supports multiple platform multiple versions. Some of platform doesn't have features you expect or include file is different.
> 
> It is another topic but you merged master to your PR. Instead of do that, please **rebase** you PR from updated master. In addition, please clean up your commits.

Sorry, I'm new to git. I followed some online instructions on how to rebase. I don't mind admitting I did it wrong. Also, what's wrong with the commits? Is it the commit messages?

**Comment by redboltz** [comment]
> > https://github.com/msgpack/msgpack-c/pull/859/checks?check_run_id=592575691#step:5:145
> > Is seems that it is caused by M_PI. Please fix it.
> > msgpack-c supports multiple platform multiple versions. Some of platform doesn't have features you expect or include file is different.
> > It is another topic but you merged master to your PR. Instead of do that, please **rebase** you PR from updated master. In addition, please clean up your commits.
> 
> Sorry, I'm new to git. I followed some online instructions on how to rebase. I don't mind admitting I did it wrong. Also, what's wrong with the commits? Is it the commit messages?

A key point is keeping commit tree clean.
Here is a good document(I didn't read it completely).

https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

In this case, you need to do three things to keep commit and pull request clean.

1. Rebase your branch from updated master
2. Squash commits.
3. Force push the branch.

After do that, let's discuss about required tests.

**Comment by pfeatherstone** [comment]
So i think i've rebased. I've changed the use of M_PI to a custom #define. That's commited and I can see it in the logs here. I don't understand how the windows test isn't running on the updated branch.

**Comment by pfeatherstone** [comment]
So all good ?

**Comment by redboltz** [comment]
> So all good ?

No. Commit history is very messy.
https://github.com/msgpack/msgpack-c/pull/859/commits

Sorry I don't have time to tell you how to use git.

**Comment by pfeatherstone** [comment]
> > So all good ?
> 
> No. Commit history is very messy.
> https://github.com/msgpack/msgpack-c/pull/859/commits
> 
> Sorry I don't have time to tell you how to use git.

@redboltz Fair enough. I can just include the main file with the adaptors in my project. I can't stand using forks. If you want I can just delete the PR and my fork

**Comment by redboltz** [comment]
Ok, please keep the PR open.

When I have time in the future, I would take over the PR.

**Comment by redboltz** [comment]
Due to C and C++ part of msgpack-c separation, the PR cannot be merged to master even if the contents of the PR is updated.
The target branch should be updated to cpp_master.

So I close the PR. And when adding complex support, I create the PR for cpp_master.

**Comment by pfeatherstone** [comment]
Also, i'm not sure if the way i was doing it was correct. I was serialising complex<type> just like pair<type>. I don't know if that's the standard way of doing it (even though the msgpack spec doesn't specify how to serialise complex numbers). I guess if there is no standard, you can make it up. Since complex is an arithmetic type, it would be far better to add it to the msgpack specification as a 'native' format. Then other languages would know how to distinguish pair<type> and complex<type>. At the moment, it feels very hacky. So maybe it would be more appropriate to add a feature request to the msgpack standard.

**Comment by redboltz** [comment]
> Also, i'm not sure if the way i was doing it was correct. I was serialising complex just like pair. I don't know if that's the standard way of doing it (even though the msgpack spec doesn't specify how to serialise complex numbers). 

I think that using ARRAY is appropriate choice like as `std::pair` under the current MessagePack format. Because it is the minimal type to express real and imaginary part of the complex type.

> I guess if there is no standard, you can make it up. Since complex is an arithmetic type, it would be far better to add it to the msgpack specification as a 'native' format. Then other languages would know how to distinguish pair and complex. At the moment, it feels very hacky. So maybe it would be more appropriate to add a feature request to the msgpack standard.

MessagePack format is defined https://github.com/msgpack/msgpack/blob/master/spec.md.
If you want to add complex type as an official format, I think that you need to use EXT types
 https://github.com/msgpack/msgpack/blob/master/spec.md#extension-types. 

Recently Timestamp is added.

I found some issues relate to complex type https://github.com/msgpack/msgpack/issues?q=is%3Aissue+is%3Aopen+complex

You can post your proposal as an issue for msgpack (not msgpack-c).

**Pull request closed without merging**
