### PR TITLE
Add Msgpack:: namespace to CMake exports

### PR DESCRIPTION
**Pull request by ChisholmKyle**
Fix for issue #801

### CODE REVIEW

**Comment by herbrechtsmeier** [comment]
This breaks backward compatibility and shouldn't work with embedded builds which adds msgpack-c as a subdirectory. You need to adapt the `msgpack-config.cmake.in` file.

**Comment by ChisholmKyle** [comment]
Ok finally got around to this - I modified the `msgpack-config.cmake.in` file. Can't be certain I'm doing it right - I simple added the namespace.

It is a backwards compatibility breaking change, but it also addresses a bug in the CMake build system (Issue #801)
What do you mean it doesn't work with embedded builds?

If it's painful for some users to add namespace Msgpack::, do you think it's reasonable to expect they can write their own FindMsgpack module, use PkgConfig, or even manually add the library and headers in their CMake files?

**Comment by redboltz** [comment]
@ChisholmKyle , thank you for updating the PR. @herbrechtsmeier , could you review updated one?

**Comment by herbrechtsmeier** [comment]
@ChisholmKyle CMake change the `add_library` behaviour of the `ALIAS` type and thereby breaks our use case. According to the CMake documentation we shouldn't use the `ALIAS`:

> The <target> may not be an Imported Target or an ALIAS.

The main problem is the msgpack-c handling of the shared and static libraries. Normally CMake use the `BUILD_SHARED_LIBS` to build a shared OR static library. Both libraries use the same target name and don't exist together. Msgpack-c build both libraries and I add the alias to ensure that the target `mspgackc`always exist. Regarding the documentation this is a misuse of the target alias.

@redboltz Do you know the use case why msgpack-c build both libraries?

@ChisholmKyle I think we should avoid a breaking change if possible. Furthermore we should avoid an additional breaking change later on. This means the new CMake API should be well defined.

@ChisholmKyle  Which an embedded build I mean you put msgpack-c into a subdirectory and build msgpack-c together with your code. But I realise that it is possible to skip the `find_package(msgpack-c)` command. This means we could remove the `if` check of the targets from the `msgpack-config.cmake.in`. You could embedded msgpack-c into your project with the following two lines:
```
add_subdirectory(msgpack-c)
set(CMAKE_DISABLE_FIND_PACKAGE_msgpack 1)
```

If we add a namespace to the targets we have to add alias for our build targets to support an embedded build. Otherwise the targets with namespace are not available.

**Comment by redboltz** [comment]
> @redboltz Do you know the use case why msgpack-c build both libraries?

No I don't know the usecase.
I think that switching build is good enough.
I mean something like
* Build shared library on `msgpack-c/build_shared`.
* Build static library on `msgpack-c/build_static`.

I don't come up any usecase that requires both shared and static library all at once.

**Comment by herbrechtsmeier** [comment]
I just realise that I check an old documentation.
> The <target> may not be a non-GLOBAL Imported Target or an ALIAS.

This means we could use the alias but we still need aliases with namespace for all libraries. Furthermore we could ensure backward compatibly if we add an alias for the old names inside the `msgpack-config.cmake.in`. Thereby we could remove the first target check because the file shouldn't be required for embedded build.

I would propose all lower case for the namespace to be consistent with the package name. I don't found a naming convention for the namespace and the CMake modules follow different rules.

**Comment by herbrechtsmeier** [comment]
@redboltz Does this means we should change the behaviour and update the `CMakeLists.txt`?

**Comment by redboltz** [comment]
> @redboltz Does this means we should change the behaviour and update the CMakeLists.txt?

I think that keeping the behavior https://github.com/msgpack/msgpack-c/pull/722#issue-208502084 is better.

I'm only using C++ part of msgpack-c. So I don't build libraries. So I didn't come up with usecase. But someone expects keeping the original behavior.

**Comment by herbrechtsmeier** [comment]
@redboltz The target names should be kept or do you want to rename something?

**Comment by herbrechtsmeier** [comment]
@ChisholmKyle Do you want to change the code or should I take over?

**Comment by redboltz** [comment]
> @redboltz The target names should be kept or do you want to rename something?

I prefer keeping the target name. But I'm not expert of cmake, I don't know how target name effects to output filenames.

I think that the output library filename should be as follows:

* On Linux
  * shared library
    * libmsgpackc.so
  * static library
    * libmsgpackc.a
* On Windows
  * shared library
    * msgpackc.dll (+ import library msgpackc.lib?)
  * static library
    * msgpackc.lib

**Comment by herbrechtsmeier** [comment]
You could set the library name independent of the target name. This is already done for the static library. At the moment the package is named `msgpack` but the targets are named `msgpackc`. Furthermore you don't know if the `msgpackc` target is a static of shared library. Some CMake modules use a PACKAGENAME_USE_STATIC variable to decide which library should be used.

**Comment by herbrechtsmeier** [comment]
@ChisholmKyle @redboltz The `add_library` with `ALIAS` and a namespace doesn't work with older CMake versions (for example 3.10.2):
> add_library cannot create ALIAS target "msgpackc-static" because target
  "msgpack::msgpackc-static" is IMPORTED

**Comment by redboltz** [comment]
> @ChisholmKyle @redboltz The `add_library` with `ALIAS` and a namespace doesn't work with older CMake versions (for example 3.10.2):
> > add_library cannot create ALIAS target "msgpackc-static" because target
  "msgpack::msgpackc-static" is IMPORTED

What can we do? Increase minimum version or something else?

```cmake
CMAKE_MINIMUM_REQUIRED (VERSION 2.8.12)
```

**Comment by herbrechtsmeier** [comment]
@redboltz The problem is the CMake version on the build system.

1. We could simple remove the alias and the user need to select the shared (msgpackc) or static (msgpackc-static) target.
2. We could add the namespace and enable the alias only if the cmake version support it.
3. We could copy the behaviour of #722 and change the target names accordingly. This means msgpackc represents the shared library if available and the static library otherwise. The target msgpackc-static is only available if both are build.

**Comment by redboltz** [comment]
Let me clarify. All of 1, 2, and 3 are required for achieve the goal? Or they are exclusive choice?

I understand that the current master can work as I expected only if cmake version is newer.
What happened if cmake is old? Even if cmake is old, can we implement #722 behavior using 3?

**Comment by herbrechtsmeier** [comment]
The numbers are exclusive choices.

It looks like the current master doesn't work if you disable the shared library. The current master only work with an extended version of this patch and would be solution 2.

If we use solution 2 and you use an older CMake and you don't build the shared library the target msgpackc wouldn't exist.

The solution 3 works with any version because it doesn't use an alias. Instead it change the target name.

**Comment by herbrechtsmeier** [comment]
I have create a patch (herbrechtsmeier/msgpack-c@38d00c1) for solution 3.
Without the exact use case of the msgpackc-static target it is hard to know if the solution works for everybody.

**Comment by redboltz** [comment]
@herbrechtsmeier ,thank you for detail explain. I think that 3 is the best solution of them.
Changing the target name is acceptable.

Could you go forward with the approach 3?

**Comment by ChisholmKyle** [comment]
@herbrechtsmeier thank you for all the explanation and the patch. I've learnt a lot about CMake. 
Go ahead and take over with your patch for solution 3 (herbrechtsmeier/msgpack-c@38d00c1) and we can close this request.

**Comment by herbrechtsmeier** [comment]
I hava create a new pull request (#804) for solution 3.

**Comment by redboltz** [comment]
@herbrechtsmeier , thank you very much. After #804 will be checked by @ChisholmKyle , I will merge #804 and close #802.

**Comment by ChisholmKyle** [comment]
I did a basic test on fix #804 and looks good to me.

**Comment by redboltz** [comment]
This PR is covered by #804 so I close it.

**Pull request closed without merging**
