### PR TITLE
cmake: Remove alias from package config

### PR DESCRIPTION
**Pull request by herbrechtsmeier**
The cmake target of an alias may not be an Imported Target.
Always build the msgpackc target and only build the msgpackc-static
target if both should be build to fix issue #801. Thereby the type
(shared or static) of the msgpackc target depends on the build
configuration.

### CODE REVIEW

**Comment by herbrechtsmeier** [comment]
@ChisholmKyle Could you please test and check if it fix your issue.

**Comment by ChisholmKyle** [comment]
Ok I tried it!

    mkdir cmake-build && cd cmake-build
    cmake -G "Unix Makefiles" \
      -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_SHARED_LIBS=OFF \
      -DMSGPACK_ENABLE_SHARED=OFF \
      -DMSGPACK_CXX11=ON \
      -DMSGPACK_BUILD_EXAMPLES=OFF \
      -DMSGPACK_BUILD_TESTS=OFF \
      -DCMAKE_INSTALL_PREFIX=/usr/local \
      ..
    make
    sudo make install

Then in a sample project CMakeFiles.txt it works:

    find_package(msgpack REQUIRED)
    target_link_libraries(msg_example msgpackc-static)

Also this works with the static only build

    find_package(msgpack REQUIRED)
    target_link_libraries(msg_example msgpackc)

I didn't try C++ headers, my sample program just uses the C interface but it looks good!

**Comment by ChisholmKyle** [comment]
I also tried a non-standard install location:
Ok seems to work. For static only build:

    mkdir cmake-build && cd cmake-build
    cmake -G "Unix Makefiles" \
      -DCMAKE_BUILD_TYPE=Release \
      -DMSGPACK_ENABLE_SHARED=ON \
      -DMSGPACK_CXX11=ON \
      -DMSGPACK_BUILD_EXAMPLES=OFF \
      -DMSGPACK_BUILD_TESTS=OFF \
      -DCMAKE_INSTALL_PREFIX=/tmp/local \
      ..
    make
    sudo make install

Then in a sample project CMakeFiles.txt it works without adding custom path to target_include_directories thanks to CMake magic!:

    set(CMAKE_FIND_ROOT_PATH "/tmp/local")
    find_package(msgpack REQUIRED)
    target_link_libraries(
        sv_example
        msgpackc)

**Comment by herbrechtsmeier** [comment]
@ChisholmKyle Please don't use `BUILD_SHARED_LIBS` together with `MSGPACK_ENABLE_SHARED` and `MSGPACK_ENABLE_STATIC` because they are mutually exclusive.

@ChisholmKyle There must be a problem in your test because the `msgpackc-static` target is only created if you build both libraries! The idea is that a project always use the target 'msgpackc' and the distributor / integrator could decide if he want to use a dynamic or static library for msgpack.

**Comment by ChisholmKyle** [comment]
OK I think I installed the wrong branch. Now it behaves as expected:

```bash
mkdir cmake-build && cd cmake-build
cmake -G "Unix Makefiles" \
  -DCMAKE_BUILD_TYPE=Release \
  -DMSGPACK_ENABLE_SHARED=OFF \
  -DMSGPACK_CXX11=ON \
  -DMSGPACK_BUILD_EXAMPLES=OFF \
  -DMSGPACK_BUILD_TESTS=OFF \
  -DCMAKE_INSTALL_PREFIX=/usr/local \
  ..
make
sudo make install
```

Produces only a static /usr/local/lib/libmsgpackc.a and does not work with -static suffix

    find_package(msgpack REQUIRED)
    target_link_libraries(msg_example msgpackc)

**Comment by ChisholmKyle** [comment]
Non-standard installation path with `MSGPACK_ENABLE_SHARED` turned ON also works. Both `msgpackc-static` and `msgpackc` target link libraries work.

```bash
mkdir cmake-build && cd cmake-build
cmake -G "Unix Makefiles" \
  -DCMAKE_BUILD_TYPE=Release \
  -DMSGPACK_ENABLE_SHARED=ON \
  -DMSGPACK_CXX11=ON \
  -DMSGPACK_BUILD_EXAMPLES=OFF \
  -DMSGPACK_BUILD_TESTS=OFF \
  -DCMAKE_INSTALL_PREFIX=/tmp/local \
  ..
make
sudo make install
```

**Comment by redboltz** [comment]
It seems that some commits are pushed. It the PR ready to merge?

There is no rush, I'm just confirming.

**Comment by herbrechtsmeier** [comment]
@redboltz Sorry, I forget to inform you. Please review the pull request. Especially the additional test need a review.

**Comment by redboltz** [comment]
It looks good to me. I didn't understand what does embedded mean at first. But finally, I understand that it is the test case for a user project that requires msgpack-c and finds it using find_package.

**Pull request merged**
