### PR TITLE
Fix 763

### PR DESCRIPTION
**Pull request by redboltz**

### CODE REVIEW

**Comment by thpica** [comment]
Thank you for the swift fix.
This passes my tests too.
LGTM :+1:

**Comment by redboltz** [comment]
@thpica , thank you for checking!

**Comment by thpica** [comment]
Hi @redboltz do you know when this will be in a tagged release?
I would love to remove my ugly workaround :slightly_smiling_face: 
(https://github.com/msgpack/msgpack-c/pull/755 would also be nice as I am using the visitor pattern too)

I can live without it, so no pressure :slightly_smiling_face:

**Comment by thpica** [comment]
https://github.com/msgpack/msgpack-c/releases/tag/cpp-3.2.0 :pray:

**Pull request merged**
