### PR TITLE
Fix endianness detection on OpenWrt

### PR DESCRIPTION
**Pull request by jonitis**
At least on trunk OpenWrt with MUSL libc runtime the arpa/inet.h does not define __BYTE_ORDER.
Look additionally into sys/param.h.

### CODE REVIEW

**Comment by redboltz** [comment]
I am looking for a good way to detect endian in many platforms. And I send a pull request. I believe that it is a portable solution. See https://github.com/msgpack/msgpack-c/pull/312

However, it is a big change. So I am wainting a review by @nobu-k, another commiter.

Could you test #312 on your environment?

**Comment by jonitis** [comment]
Hello,
Thanks for head-ups. At the moment we are using v1.1, but this new patch is for trunk. I will try to test #312.

**Comment by redboltz** [comment]
@jonitis , thank you!
I updated my comment a little.

**Comment by jonitis** [comment]
I've tested the #312. And in our environment (BE MIPS, OpenWrt trunk + musl) it defines BOTH MSGPACK_ENDIAN_LITTLE_BYTE and MSGPACK_ENDIAN_BIG_BYTE. So something is broken at either side. BTW I had to fix this error:
Makefile.am: error: required file './README' not found
by copying README.md to README

**Comment by jonitis** [comment]
Sorry, my fault. When checked with #if then everything is correct - MSGPACK_ENDIAN_BIG_BYTE is defined

**Comment by redboltz** [comment]
Thank you for testing!

> BTW I had to fix this error:
> Makefile.am: error: required file './README' not found by copying README.md to README

It seems that you didn't run ./bootstrap, See https://github.com/msgpack/msgpack-c#using-autotools

bootstrap copies README.md to README if README doesn't exist. Could you test it?

**Comment by jonitis** [comment]
Ok. Obviously should work.

**Comment by redboltz** [comment]
Fixed by #312.

**Pull request closed without merging**
