### PR TITLE
Improve bin printer for unprintable characters.

### PR DESCRIPTION
**Pull request by iphydf**
msgpack_object_print used fwrite to write binary data to a stream. The intention
of the function is to produce a human-readable representation of the object for
debugging purposes. Having arbitrary data dumped as is can cause issues with
terminals that interpret it as control sequences.

This change prints printable characters as is and unprintable characters as
hex-escapes ("\xNN"). Note that UTF-8 encoded characters will now be printed as
escaped sequence of UTF-8 bytes. This is an acceptable compromise, as doing
otherwise would require a light form of UTF-8 decoding and BIN-typed objects
should not be used to transport UTF-8 strings anyway (STR should be used
instead).

### CODE REVIEW

**Comment by redboltz** [comment]
Hi, @iphydf. Thank you for sending the PR. I think that EXT format family's data part should use the same printing function as BIN. What do you think?
https://github.com/msgpack/msgpack/blob/master/spec.md#formats-ext

**Comment by iphydf** [comment]
Agreed, changed my commit to do this.

**Comment by redboltz** [comment]
Thank you for updating the PR. I will merge the PR to master.

**Comment by redboltz** [comment]
merged.

**Pull request merged**
