### PR TITLE
Fixed #247.

### LINKED ISSUE #247: Packing int numbers should not produce uint results
When packing an positive int number, say 1427252004348, it is packed into a uint number, based on the code for `pack_imp_int64`. The spec says:

> If an object can be represented in multiple possible output formats, serializers SHOULD use the format which represents the data in the smallest number of bytes.

However, I don't think uint should be used instead of int. Also, in this case, both int and uint encodes to the same number of bytes.

### PR DESCRIPTION
**Pull request by redboltz**
Re-designed packing algorithm to improve maintenanceability.
Added msgpack header checking tests.

### CODE REVIEW

**Comment by redboltz** [comment]
I've noticed that my PR has a problem. int/uint has a higher priority than serialized size. I will fix it.

**Comment by thinxer** [comment]
I don't think packing signed int into unsigned is a good idea. Actually I'm trying to communicate with a Go program. See [here](https://github.com/tinylib/msgp/wiki/Type-Mapping-Rules) and https://github.com/tinylib/msgp/pull/63. Though the spec says smaller encoding is preferred, this will introduce more confusion and is more error-prone.

Anyway, let's participate in the discussion at https://github.com/msgpack/msgpack/issues/164 and make the spec clearer.

**Comment by redboltz** [comment]
Fixed https://github.com/msgpack/msgpack-c/pull/250#issuecomment-86346704

**Comment by redboltz** [comment]
@thinxer , thank you for the comment. I will join the msgpack format discussion.

**Comment by redboltz** [comment]
See #247

**Pull request closed without merging**
