### PR TITLE
Add MSGPACK_ENABLE_SHARED option, defaulting to ON

### PR DESCRIPTION
**Pull request by jen20**
This allows building just static libraries using the CMake build, which is useful if your product is entirely statically linked. By default there is no change to the output - MSGPACK_ENABLE_SHARED must be explicitly set to false to disable building the shared library.

### CODE REVIEW

**Comment by redboltz** [comment]
Thank you for sending the PR. It looks good to me. I don't have much time right now. I will merge it next week.

**Comment by redboltz** [comment]
I got the following error when I set -DMSGPACK_ENABLE_SHARED=OFF:

```
[kondo@msboltz] $ cmake -DMSGPACK_ENABLE_SHARED=OFF ..                                                                                                         -- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kondo/work/msgpack-c/build
[kondo@msboltz] $ make                                                                                                                                         [  3%] Building C object CMakeFiles/msgpack-static.dir/src/unpack.c.o
[  6%] Building C object CMakeFiles/msgpack-static.dir/src/objectc.c.o
[  9%] Building C object CMakeFiles/msgpack-static.dir/src/version.c.o
[ 12%] Building C object CMakeFiles/msgpack-static.dir/src/vrefbuffer.c.o
[ 16%] Building C object CMakeFiles/msgpack-static.dir/src/zone.c.o
Linking C static library libmsgpack.a
[ 16%] Built target msgpack-static
[ 19%] Building CXX object test/CMakeFiles/buffer.dir/buffer.cpp.o
Linking CXX executable buffer
/usr/bin/ld: cannot find -lmsgpack
collect2: error: ld returned 1 exit status
test/CMakeFiles/buffer.dir/build.make:88: recipe for target 'test/buffer' failed
make[2]: *** [test/buffer] Error 1
CMakeFiles/Makefile2:1026: recipe for target 'test/CMakeFiles/buffer.dir/all' failed
make[1]: *** [test/CMakeFiles/buffer.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by jen20** [comment]
Let me look into this, I wasn't building with GTest available so likely didn't hit this. Interesting that the CI server also didn't.

**Comment by redboltz** [comment]
When MSGPACK_ENABLE_SHARED is ON, the default setting, no errors are occurred. MSGPACK_ENABLE_SHARED is introduced by this PR. So travis-ci doesn't test with -DMSGPACK_ENABLE_SHARED=OFF. 
Of course, you can add -DMSGPACK_ENABLE_SHARED=OFF setting to travis-ci. However currently 32 matrix of tests are running. It's running parallely, but resources are limited. It takes a long time. If -DMSGPACK_ENABLE_SHARED=OFF setting is added to the matrix, 48 tests would run. See https://github.com/msgpack/msgpack-c/blob/master/.travis.yml
The test matrix is not automatically generated, it's not an elegant, so you can add a special test case with -DMSGPACK_ENABLE_SHARED=OFF.

I think that modifying travis-ci settings are a little complicated. I will merge the PR when the error that I pointed out would be fixed. I mean updating travis-ci setting is not mandatory.

**Comment by redboltz** [comment]
In build_cmake.sh, SHARED is not always $5 due to BOOST_INC, so I added BOOST_INC to all .travis.yml environment. Then merged. Thanks.

**Comment by jen20** [comment]
Thanks!

**Pull request merged**
