### PR TITLE
Implement issue #923: Make boost timer optional

### PR DESCRIPTION
**Pull request by VorpalBlade**
Implement issue #923: Make boost timer optional. This helps when building for embedded systems where not all of boost is available, as boost timer is only used by the examples.

### CODE REVIEW

**Comment by VorpalBlade** [comment]
I do not understand why some of the Windows builds have failed (or if it is even related to my changes at all). I would appreciate some help with that, as I do not have access to a Windows machine to test on.

**Comment by redboltz** [comment]
I'm not sure but a warning is reported at the line you modified.
https://ci.appveyor.com/project/redboltz/msgpack-c/builds/35786211/job/5edi6ffwtn4fjbk4#L233

It might caused by cmake version. (OPTIONAL_COMPONENTS might not be supported).

You can check cmake behavior adding appveyor.yml on your repository.
https://github.com/msgpack/msgpack-c/blob/cpp_master/appveyor.yml

**Comment by VorpalBlade** [comment]
OPTIONAL_COMPONENTS seems to be available already in 3.0.2, which is the oldest version for which documentation is available via the official website: https://cmake.org/cmake/help/v3.0/command/find_package.html

And on the other end of the version spectrum, I personally have the newest version from the upstream APT repository as of writing (3.18.4) installed locally.

It appears from the build failure that the issue affects Visual Studio older than 2013 (2015 builds fine).

Reading up on https://cmake.org/cmake/help/latest/policy/CMP0074.html it doesn't seem likely to be the problem, though BOOST_ROOT is defined in appveyor.yml. I don't however see why my change would change this at all either way, especially to result in it complaining about missing chrono and system (which were and still are required).

Is it possible AppVeyor updated something on their side and broke the build? Are you able to manually trigger a build of the cpp_master branch to verify that it still works?

**Comment by redboltz** [comment]
> Is it possible AppVeyor updated something on their side and broke the build? Are you able to manually trigger a build of the cpp_master branch to verify that it still works?

I just re-run appveyor. But got error.

msgpack-c is used by older compiler users. So I need to keep CI success.
You can setup appveyor on your github environment.
Please analyze the problem on your environment. If you push or force-push to the PR, then whole CI process is automatically invoked.
I recommend that debug on your enviromnent and then push or force-push the PR.

**Comment by VorpalBlade** [comment]
Turns out there was a strange hack in the appveyor.yml file to remove the components for older MSVC versions. This needed adapting after my changes.

**Comment by redboltz** [comment]
> Turns out there was a strange hack in the appveyor.yml file to remove the components for older MSVC versions. This needed adapting after my changes.

Whoa, I didn't remember the original hack. Thank you for updating the PR.

**Pull request merged**
