### PR TITLE
Bump minimum cmake version to 3.5 to avoid deprecation warning

### PR DESCRIPTION
**Pull request by dundargoc**
Bump minimum cmake version to 3.5 to avoid deprecation warning

Building msgpack gives currently gives the following warning:
"CMake Deprecation Warning at CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions."

Reuse same solution as fc18087cdfaadec0b905643f93950387e797da08 as the
policy CMP0060 introduced in cmake 3.3 causes problems with when linking
for 32-bit otherwise.

### CODE REVIEW

**Comment by redboltz** [comment]
Thank you for sending the PR. 
The current cmake minimum required version is 2.8.12 because CentOS7's cmake package version is 2.8.12.
According to https://www.centos.org/centos-linux/ , CentOS 7 support will finish on June 30th, 2024.
After CentOS 7 will finish, then msgpack-c can update cmake minimum requred version.
The updated version would be  the minimum version that is contains by major distribution.

So if you want to merge the PR before June 30th, 2024, you need to support 2.8.12. Something conditional branch in CMakeLists.txt is required.

**Comment by dundargoc** [comment]
Aren't there two versions of cmake in centos? I think one is `cmake` and one is `cmake3`, which should be up to date.

**Comment by redboltz** [comment]
> Aren't there two versions of cmake in centos? I think one is `cmake` and one is `cmake3`, which should be up to date.

I could't find cmake3 package in CentOS7.
https://centos.pkgs.org/7/centos-x86_64/
Am I missing something?

**Comment by dundargoc** [comment]
Huh, I think I mixed it up with the cmake3 from the epel repo. My bad.

I've added a conditional. Please take a look again.

**Comment by redboltz** [comment]
Thank you for updating! Looks good to me.

**Pull request merged**
